import { Inter } from "next/font/google";
import "./globals.css";
// import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

const styleclass = "";


export const metadata = {
  title: "HTMS | Knowledge Base",
  description: "Generated by create next app"
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={styleclass}>
      <body >{children}</body>
    </html>
  );
}
